### ISSUE TITLE
MATEBOOK D15 2020 I5 10210

### ISSUE THREAD

**Issue by Lws0530** [ske1996/Matebook-D14-2020-hackintosh#1]
其他功能如描述正常 但是触控板还是不能使用 是我操作不当还是怎么样。。

**Comment by ske1996** [comment]
首先，这个是给d14做的
关于d15是否通用尚且未知。
另外pm981硬盘版本的机器在触控板上可能有问题

试试如下操作：
1.在config中开启voodoops2controler的voodooinput
2.在config中disable掉SSDT-I2CxConf.aml

以上操作可采取排列组合式，比如做1不做2，做2不做1，1与2都做，这样试试

不行的话就自行百度触摸板定制教程，以上操作的教程也自行百度
