### ISSUE TITLE
Matebook14 2020

### ISSUE THREAD

**Issue by Benson17688** [ske1996/Matebook-D14-2020-hackintosh#11]
我装完发现没wifi这个选项，我是哪里做错了吗，蓝牙到可以用

**Comment by ske1996** [comment]
这个项目是给D14用的，你mb14不要用这个项目的efi

**Comment by Benson17688** [comment]
啊我可以用，适用的，那时候是我不会装wifi驱动，哈哈，谢谢你

ske1996 <notifications@github.com> 於 2021年2月19日 週五 下午2:48寫道：

**Comment by ske1996** [comment]
不是，是一些acpi以及缓冲帧的问题，你去用我另一个项目的，这样比较好
