### ISSUE TITLE
20210506的efi问题

### ISSUE THREAD

**Issue by xiangbeta** [ske1996/Matebook-D14-2020-hackintosh#14]
首先感谢大神，本人一直正常使用20201012的efi，用的卡琳娜，刚看到efi更新了，下载更换之后，进度条走到一半就黑屏了，不知道啥原因，更换回20201012正常。

**Comment by ske1996** [comment]
你这没日志我也看不出问题啊，我没改什么东西啊

**Comment by ske1996** [comment]
[config.plist.zip](https://github.com/ske1996/Matebook-D14-2020-hackintosh/files/6447179/config.plist.zip)
把这个替换到新的EFI里覆盖，然后出问题了给我日志

**Comment by xiangbeta** [comment]
> [config.plist.zip](https://github.com/ske1996/Matebook-D14-2020-hackintosh/files/6447179/config.plist.zip)
> 把这个替换到新的EFI里覆盖，然后出问题了给我日志

替换后可以进桌面了 但是wifi失效

**Comment by xiangbeta** [comment]
> [config.plist.zip](https://github.com/ske1996/Matebook-D14-2020-hackintosh/files/6447179/config.plist.zip)
> 把这个替换到新的EFI里覆盖，然后出问题了给我日志

替换后可以进桌面了 谢谢

**Comment by xiangbeta** [comment]
> > [config.plist.zip](https://github.com/ske1996/Matebook-D14-2020-hackintosh/files/6447179/config.plist.zip)
> > 把这个替换到新的EFI里覆盖，然后出问题了给我日志
> 
> 替换后可以进桌面了 谢谢

然后序列号变成了123456

**Comment by xiangbeta** [comment]
不错不错 更新后wifi能到百兆以上了 感谢大神

**Comment by ske1996** [comment]
> > > [config.plist.zip](https://github.com/ske1996/Matebook-D14-2020-hackintosh/files/6447179/config.plist.zip)
> 
> > > 把这个替换到新的EFI里覆盖，然后出问题了给我日志
> 
> > 
> 
> > 替换后可以进桌面了 谢谢
> 
> 
> 
> 然后序列号变成了123456

三码你没自己定制过吗？我在注意事项里写了，用之前第一件事就是定制三码，具体的教程自己百度

**Comment by xiangbeta** [comment]
> > > > [config.plist.zip](https://github.com/ske1996/Matebook-D14-2020-hackintosh/files/6447179/config.plist.zip)
> > 
> > 
> > > > 把这个替换到新的EFI里覆盖，然后出问题了给我日志
> > 
> > 
> > > 
> > 
> > 
> > > 替换后可以进桌面了 谢谢
> > 
> > 
> > 然后序列号变成了123456
> 
> 三码你没自己定制过吗？我在注意事项里写了，用之前第一件事就是定制三码，具体的教程自己百度

定制过的 用你这个config替换后就变了
