### ISSUE TITLE
提醒大神 闲鱼上有人使用EFI获利。

### ISSUE THREAD

**Issue by xiangbeta** [ske1996/Matebook-D14-2020-hackintosh#15]
![微信图片_20210515172501](https://user-images.githubusercontent.com/77616613/118355430-955a8900-b5a2-11eb-88ae-1256176bc2d5.jpg)
![微信图片_20210515172510](https://user-images.githubusercontent.com/77616613/118355432-968bb600-b5a2-11eb-917b-585c759810c2.jpg)

**Comment by ske1996** [comment]
见怪不怪了，matebook系列的黑苹果都所有店家用的efi基本都是我的

**Comment by ske1996** [comment]
谢谢你告诉我，我项目挂了license，我这都掉过他们的鱼，有他们用我efi给人装机赚钱的证据，等他们一个个的赚个5-6w的时候就够我去告他们的成本了
