### ISSUE TITLE
Matebook D14 2020 - Big Sur - Freeze while formatting internal SSD 

### ISSUE THREAD

**Issue by gianmarcofavaretto** [ske1996/Matebook-D14-2020-hackintosh#16]
Hi, i have a Matebook D14 2020 and i'm trying to install BIG SUR 11.4 (same problem with the latest Catalina). The installer is loaded correctly but when i try to format internal SSD with "utility disk" the process freeze after 30 seconds.
If i reboot the Matebook, the disk is not formatted. i can't continue the installation process.
Do you have a suggestion to solve this issue ?
i tried to enable / disable USBInjectall.kext but with no luck. 
I'm using the EFI for Matebook 2020 D14 .
Many thanks.

Gianmarco

**Comment by ske1996** [comment]
> Hi, i have a Matebook D14 2020 and i'm trying to install BIG SUR 11.4 (same problem with the latest Catalina). The installer is loaded correctly but when i try to format internal SSD with "utility disk" the process freeze after 30 seconds.
> 
> If i reboot the Matebook, the disk is not formatted. i can't continue the installation process.
> 
> Do you have a suggestion to solve this issue ?
> 
> i tried to enable / disable USBInjectall.kext but with no luck. 
> 
> I'm using the EFI for Matebook 2020 D14 .
> 
> Many thanks.
> 
> 
> 
> Gianmarco

try to redownload macos image and flash it to another usb stick,got same problem before,and i did that,and succeed

**Comment by gianmarcofavaretto** [comment]
Many thanks, i will try this afteroon. if i will have success doing that i will donate you something on your paypal. Thanks for your advice.

Gianmarco

**Comment by gianmarcofavaretto** [comment]
In the BIOS i see that the SSD is :  SAMSUNG MZVLB512HBJQ-00000 512 GB . i will investigate on what's the correcto model of my ssd.

Gianmarco

**Comment by ske1996** [comment]
> Many thanks, i will try this afteroon. if i will have success doing that i will donate you something on your paypal. Thanks for your advice.
> 
> 
> 
> Gianmarco

Even this project is not that much starred,but i think there were at least over than 100 users that they succeed to hackintoshed their matebook d14,so i think you have no reason to failure

**Comment by ske1996** [comment]
> In the BIOS i see that the SSD is :  SAMSUNG MZVLB512HBJQ-00000 512 GB . i will investigate on what's the correcto model of my ssd.
> 
> 
> 
> Gianmarco

that is pm981a,following this:

**Comment by gianmarcofavaretto** [comment]
Ok , seems i have PM981A. what image do i have to load on the SSD ? thanks
