### ISSUE TITLE
【已解决】Matebook-D14-2020 i7-10XXXu 除了hdmi都完美

### ISSUE THREAD

**Issue by 2hangchen** [ske1996/Matebook-D14-2020-hackintosh#2]

**Comment by ske1996** [comment]
我手上没有机器没法测试，能不能跟我讲讲你的hdmi有什么问题，什么表现呢

**Comment by unidbaas** [comment]
> 我手上没有机器没法测试，能不能跟我讲讲你的hdmi有什么问题，什么表现呢

呃。。。我只是在此处做一个机型的记录。我i7 10代u的机器，用这个efi，现在除了hdmi外接有问题，别的都完美了，这台机子我装了一个多月了，今天才找到相对完美的efi

**Comment by ske1996** [comment]
对，我就想知道你的hdmi用起来有什么问题，具体表现是什么？

**Comment by ske1996** [comment]
因为我手上现在没有d14的机器，没法测试，你跟我讲讲

**Comment by unidbaas** [comment]
> 对，我就想知道你的hdmi用起来有什么问题，具体表现是什么？

就是外接hdmi无信号

**Comment by ske1996** [comment]
纯粹的没信号对吗？接上后电脑会不会卡？有没有黑屏，有没有重启？

**Comment by unidbaas** [comment]
> 纯粹的没信号对吗？接上后电脑会不会卡？有没有黑屏，有没有重启？

对，电脑会变卡，但是不是很卡

**Comment by ske1996** [comment]
> > 纯粹的没信号对吗？接上后电脑会不会卡？有没有黑屏，有没有重启？
> 
> 
> 
> 对，电脑会变卡，但是不是很卡

找了个小伙伴测试了一下，现在修复了，不过我在外面，晚一点我会更新

**Comment by unidbaas** [comment]
> > > 纯粹的没信号对吗？接上后电脑会不会卡？有没有黑屏，有没有重启？
> > 
> > 
> > 对，电脑会变卡，但是不是很卡
> 
> 找了个小伙伴测试了一下，现在修复了，不过我在外面，晚一点我会更新

强啊
