### ISSUE TITLE
rom 等都修改了还是进不去啊，麻烦您看看

### ISSUE THREAD

**Issue by dora-world** [ske1996/Matebook-D14-2020-hackintosh#22]
[config.zip](https://github.com/ske1996/Matebook-D14-2020-hackintosh/files/7210696/config.zip)
开机先显示苹果logo然后加载一半后开始黑屏

**Comment by wangyu1823** [comment]
我是偶尔遇到这样的情况. 应该是核显没加载上,你看看你的cpu是不是和efi的cpu不一样?

**Comment by ske1996** [comment]
按这个格式写一下我看看，另外请附上照片或者视频以便让我理解问题，要么从按下开机开始拍个十几张，要么给个视频。具体上传方法请自行百度。

Device info（设备信息）

Matebook xx 20xx

CPU:
RAM size:
SSD model:
MacOS version:
EFI version:

Describe the bug（问题简述）


图或视频:
