### ISSUE TITLE
win10启动不了

### ISSUE THREAD

**Issue by wendao2008** [ske1996/Matebook-D14-2020-hackintosh#3]
选win10启动失败，从9.17号就开始这样了。另外，有时卡代码，需要多试几次才能人品爆发进入苹果系统

**Comment by ske1996** [comment]
第一，不要用oc引导windows系统，开机f12选windows

第二，卡代码你也得把具体的卡哪里发出来我才知道，不然等于没说

**Comment by wendao2008** [comment]
9月7日的会快速进入苹果系统，但是发现没声音和wifi

**Comment by ske1996** [comment]
我手上没有机器可以测试，但是根据我给别人装的情况来看，确实没出现你的情况，wifi肯定是有，需要efi对应系统版本才可以，还有第一次就是你要进设置，网络里看一下wifi接口有没有出来，你写的东西太模糊了，我没法解决你的问题

**Comment by wendao2008** [comment]
wifi和声音是9月7日的版本没有但可以进win，9月17日和10月11日的没问题。win启动问题应该是只能用f12来解决了。我是想知道有一定几率卡代码是不是pm981硬盘的问题。卡代码都是在Please go to https://panic.apple.com to report this panic   不知道什么原因了

**Comment by ske1996** [comment]
不是只有最后一行代码才有用，前面的代码会告诉你问题在哪里，还有，pm981上出的一切问题我难以回答，硬盘太妖，自己想办法吧

**Comment by wendao2008** [comment]
好的，垃圾pm981,服了。感谢你的回复！
